<?php
/**
 * Created by PhpStorm.
 * User: merik
 * Date: 2016/3/20
 * Time: 上午10:25
 */

class MainTask extends BaseTask
{

    protected $mongo;
    protected $database;
    protected $collextion;

    public function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $this->mongo = $this->initMongo();
        $this->database = $this->mongo->selectDB('wulo');
        $this->collection = $this->database->selectCollection('data');
    }

    public function mainAction()
    {
        $sitemap = new \Wulo\Sitemap();
        $sitemap->test();
    }
}