<?php
/**
 * Created by PhpStorm.
 * User: merik
 * Date: 2016/3/20
 * Time: 上午10:15
 */

namespace Wulo;

use Wulo, Phalcon;
class Sitemap extends Base
{
    const NEWLINE				= "\n";
    const TAB					= "\t";
    private  $rootPath          = '';
    protected $dirPath			= "/public/sitemaps";
    protected $sitemapPrefix	= 'sitemap-';
    protected $sitemapPostfix	= '.xml';
    protected $robots			= '/public/robots.txt';

    public function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub

        $this->rootPath = dirname(dirname(dirname(__FILE__)));
        $this->dirPath = $this->rootPath . $this->dirPath;
        $this->robots = $this->rootPath . $this->robots;

        echo "{$this->rootPath}\n{$this->dirPath}\n{$this->robots}\n";

    }

    public function test()
    {

    }
}