<?php
/**
 * Created by PhpStorm.
 * User: merik
 * Date: 2016/3/20
 * Time: 上午10:15
 */

namespace Wulo;

use Wulo, Phalcon;
class Sitemap extends Base
{
    const NEWLINE				= "\n";
    const TAB					= "\t";
    protected $dirPath			= '/www/iask.tw/public/sitemaps';
    protected $sitemapPrefix	= 'sitemap-';
    protected $sitemapPostfix	= '.xml';
    protected $robots			= '/www/iask.tw/public/robots.txt';

    public function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub

        echo __FILE__, __DIR__;
    }

    public function test()
    {

    }
}